# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

branches:
  except:
    - gh-pages

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O3 -Wall -Wextra -Werror -pedantic"
    - OMP_NUM_THREADS=4

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y gcc-5 g++-5 make cmake ninja-build cppcheck doxygen doxygen-latex help2man graphviz libqt4-dev qt4-qmake valgrind
  - sudo rm -f /usr/bin/gcc
  - sudo rm -f /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++

script:
  # 1) Build using GNU make
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DBUILD_DOC=ON -DCMAKE_INSTALL_PREFIX=$(pwd) ..
  - make -j4
  - make doc >/dev/null
  - make install
  - cd ..
  - rm -rf build
  # 2) Build primesieve GUI app
  - cd src/gui
  - qmake QMAKE_CXX=$CXX QMAKE_CC=$CC
  - make -j4
  - cd ../..
  # 3) Build using ninja
  - mkdir build
  - cd build
  - cmake -GNinja -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DBUILD_DOC=ON ..
  - ninja
  - ninja doc >/dev/null
  # 4) Run integration tests
  - ninja test
  - test/cpu_info
  - test/atomic
  - cd ..
  # 5) Test using valgrind
  - $CXX -Iinclude -O2 -std=c++11 -g examples/cpp/nth_prime.cpp -o nth_prime build/libprimesieve.a -lpthread
  - valgrind --error-exitcode=1 ./nth_prime 500000000
  # 6) Test using cppcheck
  - rm -rf build
  - cppcheck . -q --error-exitcode=1 -iexamples/cpp/prev_prime.cpp -iexamples/cpp/primesieve_iterator.cpp -itest/next_prime1.cpp -itest/prev_prime1.cpp
